### ISSUE TITLE
experimental result

### ISSUE THREAD

**Issue by Zhangxintong007** [MLEnthusiast/MHCLN#1]
I have runned the code for UCM, but the result of mine is different from yours. In the paper  32bit mAP of UCM is 0.904, my experimental result is 0.884955.  Is it a parameter problem?

**Comment by MLEnthusiast** [comment]
Hi. I re-ran the same code and I achieved map@20 as 0.9034. The results are different among different runs because the train and test splits are done randomly when you run `dataset_generator.py`. To get stable results you may fix the seed of python.

However, I have provided a link to the randomly chosen train and test split in the readme file of this project. You can download and verify the results I obtained.

[link] (https://drive.google.com/open?id=13D3zrX0D0vr4Uz6aiZ9H9bsBr6No3vbm)
